### ISSUE TITLE
Navbar - Hamburger icon not hiding at 769px in Firefox

### ISSUE THREAD

**Issue by AnsonH** [AnsonH/AnsonH.github.io#1]
If I'm using **Firefox Developers Edition** and the viewport width is 769px, the hamburger icon (with `hide-lg-up` class) and the navigation links (with `hide-md-down` class) both show up.

![image](https://user-images.githubusercontent.com/57580593/113285565-b3836700-931d-11eb-9760-d0496e8efc15.png)

However, this issue is not found in Chrome (and Edge too):

![image](https://user-images.githubusercontent.com/57580593/113286097-4e7c4100-931e-11eb-9d64-d8f92027d573.png)

Here's an extract from `_variables.scss`:
```scss
$breakpoints-up: (
  "medium": "481px",
  "large": "769px",
  "extra-large": "1081px",
);

$breakpoints-down: (
  "small": "480px",
  "medium": "768px",
  "large": "1080px",
);
```

Extract from `_globals.scss`:
```scss
.hide-lg-up {
  @include mixins.breakpoint-up(large) {
    display: none !important;
  }
}

.hide-md-down {
  @include mixins.breakpoint-down(medium) {
    display: none !important;
  }
}
```

Extract from `_mixins.scss`:
```scss
@mixin breakpoint-up($size) {
  @media (min-width: map-get($map: $breakpoints-up, $key: $size)) {
    @content;
  }
}

@mixin breakpoint-down($size) {
  @media (max-width: map-get($map: $breakpoints-down, $key: $size)) {
    @content;
  }
```

Therefore, at viewport width of 769px, the hamburger icon should have `display: none;` since `min-width: 769px` is satisfied.
