### ISSUE TITLE
Experience - Container height issues

### ISSUE THREAD

**Issue by AnsonH** [AnsonH/AnsonH.github.io#2]
The height `.work__container` is only equal to the height of the tabs row for some reason

![image](https://user-images.githubusercontent.com/57580593/113558850-fa7d9f00-9632-11eb-9371-f770290da78d.png)

**Comment by AnsonH** [comment]
Solution:

```scss
.work__content_section.visible {
  position: relative;
}
```
